flags=-g -Wall -Wextra -Werror -pedantic

1:
	clear;
	gcc $(flags) 1-strok.c ../getinfo.c
	./a.out
2:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/000.m
02:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/07.m
4:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/00.m
11:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/28.m
12:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/31.m
01:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/06.m
add: 
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/12.m
sub:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/19.m
mul:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/15.m
div: 
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/13.m
mod:
	clear;
	gcc $(flags) ../*.c -o test
	./test ../bytecodes/14.m
